### PR TITLE
Update Windows Installation section

### PR DESCRIPTION
**Pull request by kimjammer**
Fix typos, more professional language, fix incorrect information.

Using new WSL installation method that uses powershell and not windows features.
Add missing information about .wslconfig.
Re-add info about using WSLg that was removed.

### CODE REVIEW

**Comment by sickcodes** [comment]
Thanks so much for this @kimjammer!

Here's the draft where I was and the reason why I didn't merge it for so long, do you see anything here worth adding?

<hr>
<hr>
<hr>
  ### I'd like to run Docker-OSX on Windows
  
  Running Docker-OSX on Windows is now possible using WSL2 (Windows 10/11 + WSL Subsystem).
  
  Windows 10: Build 20175 or higher.
  
  Windows 11: Supported by default.
  
  Next, ensure you have enabled the features on your Windows. Search using the Start Menu for "Turn Windows Features on or off" and enable these checkbox; enable the following Windows Features:
  
  ```
  - Windows Subsystem For Linux
  - Windows Hypervisor Platform
  - Virtual Machine Platform
  ```
  
  Once enabled, your PC will ask to restart.
  
  You can confirm WSL2 is enabled using `wsl -l -v` in PowerShell.
  
  In PowerShell you can see available distributions to install: `wsl --install -l -o`
  
  If you only have WSL1 (WSL) but not WSL2, you will need to upgrade to WSL version 2: [see here how to upgrade from WSL1 to WSL2](https://docs.microsoft.com/en-us/windows/wsl/install#upgrade-version-from-wsl-1-to-wsl-2) in case you have already installed WSL Distro.
  
  After WSL2 has been installed, go to `C:\Users\<Your_Name>\.wslconfig` and add `nestedVirtualization=true` to the end of a file named `.wslconfig` (If the file not exist, create it).
  
  In File Explorer, you will need to `Show Hidden Files` and `Show File Extensions`.
  
  The result should be like this:
  ```
  [wsl2]
  nestedVirtualization=true
  ```
  
  Open PowerShell as Administrator and enter `Enable-WindowsOptionalFeature -Online -FeatureName Microsoft-Windows-Subsystem-Linux`
  
  Open your WSL Distro (e.g Ubuntu) via the Start Menu and check if KVM is enabled by using `kvm-ok` command, the output should be like this:
  
  ```
  $ kvm-ok
  INFO: /dev/kvm exists
  KVM acceleration can be used
  ```
  
  It's time to download and install [Docker for Windows](https://docs.docker.com/desktop/windows/install/).
  
  After installation, go to Setting and check these 2 checkbox:
  
  ```
  General -> "Use the WSL2 based engine";
  Resources -> "Enable integration with my default WSL distro"
  ```
  
  Ensure `x11-apps` is installed, in case use the command `sudo apt install x11-apps -y`
  
  From now, you have 3 way to get video output:
  
  - WSLg: is the one I use, actually is not perfect, ex. keyboard is not fully passthrough or you will see second mouse on the desktop! [Here the issue on WSLg](https://github.com/microsoft/wslg/issues/376)
  - Desktop Environment: this will give you a full linux desktop expirience but it will use a little bit of resources "RAM, CPU, GPU, etc..". I will attach an example guide but you will find a tons of guide to set a DE. [DE Example](https://www.makeuseof.com/tag/linux-desktop-windows-subsystem/)
  - VNC: You can add -vnc argument to qemu and connect to your VM via VNC Client. [Here how to](https://wiki.archlinux.org/title/QEMU#VNC)
  
  ```

**Comment by kimjammer** [comment]
I've read over your comment. Here are the major differences in my version.

- Windows 11 is now a hard requirement as Windows 10 versions with build 20000+ are not possible to obtain anymore.

- WSL is now installed differently. Instead of enabling it as a windows feature, you only have to run 'wsl --install' in an administrator powershell session.
- I elaborated on how to use WSLg.

**Comment by kimjammer** [comment]
Everything else looks wonderful, and most of that information is now in my patch!

**Comment by aarivex** [comment]
+

Makes it easier to read and matches the rest of the README.

**Comment by MikeCoder96** [comment]
instead of this:

After WSL2 has been installed, go to C:\Users\<Your_Name>\.wslconfig and add nestedVirtualization=true to the end of a file named .wslconfig (If the file not exist, create it).

In File Explorer, you will need to Show Hidden Files and Show File Extensions.

Edit like this:
In File Explorer, you will need to Show Hidden Files and Show File Extensions.

After WSL2 has been installed, go to C:\Users\<Your_Name>\.wslconfig and add nestedVirtualization=true to the end of a file named .wslconfig (If the file not exist, create it).

You have to check if the file exist and hidden but most of the time the file not exist.

**Comment by kimjammer** [comment]
Ok, I'll change the order of those instructions. With all due respect, I'm assuming you live in a non-English speaking part of the world? Your English seems to be a bit less than professional.

For the second point, installing WSL only requires that command now. See this part of [the docs](https://docs.microsoft.com/en-us/windows/wsl/install#:~:text=This%20command%20will%20enable%20the%20required%20optional%20components). The command automatically enables the required windows features.

**Comment by kimjammer** [comment]
@MikeCoder96 Also, are you sure you looked at the correct part of the PR? The text you quoted is from sickcode's comment, not my changes.

**Pull request merged**
