### PR TITLE
Add bigsur BaseSystem.img support. Use `--build-arg VERSION=11` 

### PR DESCRIPTION
**Pull request by sickcodes**
Add bigsur BaseSystem.img support. Use `--build-arg VERSION=11` or higher.

Downloads latest version currently.

If you want to select verisons, submit a PR to @acidanthera's great project to get the version option https://github.com/acidanthera/OpenCorePkg/blob/master/Utilities/macrecovery/macrecovery.py

### CODE REVIEW

**Comment by sickcodes** [comment]
bigsur

Works fine

**Comment by sickcodes** [comment]
Will upload a new `:auto-big-sur` image soon


Seeking feedback on the proposed additional Dockerfiles:

`:big-sur` DIY installation

`:auto-big-sur` pre-built image. Very large image currently, 30GB++, working on this

**Comment by trompx** [comment]
@sickcodes are you still planning to release a pre-built big sur image?

**Comment by sickcodes** [comment]
Nah Big Sur is 40G, it's not too hard to create one thought. It's safer to create your own, in fact, if you use mine, we share some keys & identifiers etc.

**Pull request merged**
