### PR TITLE
Revert glibc patch when applicable.

### PR DESCRIPTION
**Pull request by sickcodes**
We currently have a dirty fix that looks like this:

```bash
# TEMP-FIX for pacman issue
RUN patched_glibc=glibc-linux4-2.33-4-x86_64.pkg.tar.zst \
    && curl -LO "https://raw.githubusercontent.com/sickcodes/Docker-OSX/master/${patched_glibc}" \
    && bsdtar -C / -xvf "${patched_glibc}" || echo "Everything is fine."
# TEMP-FIX for pacman issue
```

This PR is just a reminder to repeat build tests until it's fixed upstream as noted:

https://github.com/sickcodes/Docker-OSX/issues/144

https://github.com/sickcodes/Docker-OSX/pull/150

https://github.com/sickcodes/Docker-OSX/pull/152

### CODE REVIEW

**Comment by Cranmmo** [comment]
Hello

**Comment by Cranmmo** [comment]
Hello

**Review by pekici — APPROVED** [review]

**Comment by sickcodes** [comment]
Regular testing until @docker fixes this issue:

```bash
git clone https://github.com/sickcodes/Docker-OSX.git
cd Docker-OSX
git config --global user.email "you@example.com"
git config --global user.name "Your Name"
git cherry-pick b79f26a50877673890dabbce2552252d75b4c03e
git commit -m "TEST GLIBC FIX GONE"
docker build -t docker-osx .
```

# FAIL
```
Step 10/53 : RUN pacman -Syu git zip vim nano alsa-utils openssh --noconfirm     && ln -s /bin/vim /bin/vi     && useradd arch -p arch     && tee -a /etc/sudoers <<< 'arch ALL=(ALL) NOPASSWD: ALL'     && mkdir /home/arch     && chown arch:arch /home/arch
 ---> Running in 3b2e9009f196
error: failed to initialize alpm library
(could not find or read directory: /var/lib/pacman/)
The command '/bin/bash -c pacman -Syu git zip vim nano alsa-utils openssh --noconfirm     && ln -s /bin/vim /bin/vi     && useradd arch -p arch     && tee -a /etc/sudoers <<< 'arch ALL=(ALL) NOPASSWD: ALL'     && mkdir /home/arch     && chown arch:arch /home/arch' returned a non-zero code: 255
```

**Comment by sickcodes** [comment]
New version: https://github.com/sickcodes/Docker-OSX/pull/321

**Pull request closed without merging**
