### PR TITLE
Simplify .ssh directory setup process in Dockerfile

### PR DESCRIPTION
**Pull request by PeterDaveHello**
Less image layer, more maintainable and readable!

### CODE REVIEW

**Comment by sickcodes** [comment]
Thank you @PeterDaveHello!

**Comment by PeterDaveHello** [comment]
Thanks @sickcodes! Do you mind me to continue simplify it like removing the duplicated `WORKDIR` instructions?

**Comment by sickcodes** [comment]
Sure, feel free to clean whatever you like :) did you like the project?

**Comment by PeterDaveHello** [comment]
Sure, the projects looks pretty cool ;)

**Pull request merged**
